name: Check Markdown links

on:
  push:
    branches:
      - main
  schedule:
    # Tuesdays at 9AM PST. GitHub Actions run in UTC.
    - cron: '0 16 * * 2'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-verbose-mode: 'yes'
